---
deployment:
  tasks:
    - export NODE_ENV=production
    - /opt/cpanel/ea-nodejs20/bin/npm install
    - /opt/cpanel/ea-nodejs20/bin/npm run build
    - rsync -a --exclude='.git' --delete-after ./build/ /home/ze0xanq7p758/public_html/
